### ISSUE TITLE
Allow override for TextField component used

### ISSUE THREAD

**Issue by noah-potter** [dmtrKovalenko/material-ui-pickers#161]
We wrap the material ui TextField pretty heavily. Could we add a prop that allows the DateTextField to use a custom TextField instead of the imported TextField?

I think a prop like `TextField` or `TextFieldComponent` that accepted this wrapped component would work pretty well. Looks like extra props already end up on DateTextField

Thoughts before I submit a PR?

**Comment by dmtrKovalenko** [comment]
Hi. no worries - feel free to open a PR - its an a lightweight and nice feature, but actually its really any chance that somewho will use material-ui and material-ui-pickers and will not use material-ui TextField? 😄

**Comment by bsinibaldi** [comment]
@dmtrKovalenko Yes and no; we're using material-ui components, but would, for example, like to be able to trigger the datepicker from a dropdown (e.g. a schedule now vs. later type thing), instead of having an interstitial step with an input. If we could customize the base component, we could change it to be a dropdown or make the TextField itself hidden, etc.

**Comment by ValentinH** [comment]
Any ETA for a new release bringing #163?
