### ISSUE TITLE
styled-components or how to style material-ui-pickers

### ISSUE THREAD

**Issue by unutoiul** [dmtrKovalenko/material-ui-pickers#191]
I'm using styled-components to style most of my material UI components and everything works fine...but not with material-ui-pickers...any idea how to style or inject css?

also how to grab different elements from material-ui-pickers and change the style?

Thanks,
Lucas

**Comment by dmtrKovalenko** [comment]
No ><
You have no ability to style pickers because its just really hard to provide high-level styling api, we have used material-ui style system (jss) and if you want you can open a PR to add ability adding classNames to each child component, but it would not be easy. 
Secondary you can fully override text-input with `TextFieldComponent` and Pickers are really pretty-looks 😸  and no really a lot of people need to override something.
