### ISSUE TITLE
Material-ui rename a Typography prop "type" to "variant"

### ISSUE THREAD

**Issue by nicky-dev** [dmtrKovalenko/material-ui-pickers#210]
![image](https://user-images.githubusercontent.com/14047941/36026461-cb69ede4-0dc9-11e8-8c39-72a5caa75bd1.png)

## Environment
| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  v1.0.0-beta.14       |
| material-ui         |   v1.0.0-beta.32      |

**Comment by gbahamondezc** [comment]
CHANGELOG reference to the change -> [Material UI Beta 32](https://github.com/mui-org/material-ui/blob/v1-beta/CHANGELOG.md)

**Comment by cherniavskii** [comment]
@nicky-dev 
Hi and thanks for taking your time on this bug report!
However, v1-beta.14 is compatible with material-ui@1-beta.31 only.

In order to support beta.32 and beta.33 in next release, we should apply all the breaking changes introduced in beta.32.
Feel free to open a PR - your help is appreciated :)

**Comment by dmtrKovalenko** [comment]
Fixed in beta.15
