### ISSUE TITLE
Per day classes and DayProps prop

### ISSUE THREAD

**Issue by noah-potter** [dmtrKovalenko/material-ui-pickers#36]
Would you approve a PR that added a handler that could attach extra classes to each rendered day? Something like:

```jsx
dayClassName(date) {
  return classnames({
    [classes.highlight]: isWeekend(date),
  })
}

<DatePicker dayClassName={dayClassName} />
```

This function would be ran when each day's className was calculated.

Also, would you support a PR that added a `DayProps` prop that would be spread onto each day's IconButton?

**Comment by sakulstra** [comment]
I would recommend to instead have a `renderDay = (day, selected) => {return <Whateveryoulike />}` function which can be passed as a prop (similar to what https://github.com/moroshko/react-autosuggest does)

**Comment by dmtrKovalenko** [comment]
@noah-potter @sakulstra 
I think we can implement both, because it would not rise the bundle size, and from other side add some flexibility of rendering. I think also would be helpful to have something like `shouldDisableDate` function, allows to disable particular dates. 
Would you like to open a pull request?

**Comment by noah-potter** [comment]
I'll take a stab at it
