### ISSUE TITLE
Week days title not logical for RTL languages

### ISSUE THREAD

**Issue by adeelshahid** [dmtrKovalenko/material-ui-pickers#361]
![screenshot from 2018-04-16 15-45-16](https://user-images.githubusercontent.com/34527/38812663-3e798488-418d-11e8-9bba-0c47d3f1c409.png)

For RTL languages,

- Arabic
- Hebrew
- Persian
- Urdu

Using first letter for **week day** would be illogical to show. Because it wouldn't have any logical meaning. Therefore we need the full name. Another reason being that RTL language are composed of ligature kind of font e.g.

For **Urdu** the weekdays are written like this۔
اتوار، پیر، منگل ، بدھ، جمعرات، جمعہ، ہفتہ

Therefore using the first letter of the alphabet would be confusing to know which weekday it is.

**Comment by dmtrKovalenko** [comment]
As far I understand you are using [jalali utils](https://github.com/alitaheri/material-ui-pickers-jalali-utils)?
If so you can apply this enhancement in the repository. I will not change default behavior for the pickers due to 1-letters days are better solution for a lot of other locales. 
Anyway you can change displaying of weekdays strings with a help of `getWeekdays()` method override in the utils. Read more [here](https://material-ui-pickers.firebaseapp.com/guides/formats)
