### ISSUE TITLE
DatePicker label animation is not consistent with MUI TextField

### ISSUE THREAD

**Issue by ajkaushik** [dmtrKovalenko/material-ui-pickers#451]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.9     |
| material-ui         |    1.0.0     |
| React               |     16.4.0    |
| Browser             |    chrome     |
| Platform            |    Windows     |

## Steps to reproduce
1. Add DatePicker (or just use demo from the documentation website)
2. Navigate to DatePicker and tab/cancel out
3. Floating label should animate properly

## Expected behavior
When field is focused or value is not null, label should be shrinked position else it should be in normal position

## Actual behavior
Once the field is navigated, label always stays in shrink mode

## Live example
https://material-ui-pickers.firebaseapp.com/demo/datepicker

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.firebaseapp.com/demo/datepicker
Check it out. After rc.10 release cleared labels displays as default mui text fields. Here left one issue that after closing the modal previous focused node gives focus and cleared field makes expanded again. 

But from where I stand - its fixed. Feel free to ask for reopen or open new issue

**Comment by LironGetJones** [comment]
I think that the problem still exists on rc.10.

As you can see at the 2 images below, the label of material-ui-pickers fields stay on top of the field, instead of going to the bottom (as it works on material-ui TextField)

It seems that material-ui-pickers fields declared with "shrink: true" on InputLabelProps of material-ui TextField (similar to the 'Number' field on the image from material-ui.

from material-ui-pickers:
![image](https://user-images.githubusercontent.com/39024480/41348492-70aaa940-6f15-11e8-97c5-e8bba24bc1dd.png)

from material-ui: 
![image](https://user-images.githubusercontent.com/39024480/41349046-4a3b0a00-6f17-11e8-8480-96aba92becc8.png)

**Comment by ajkaushik** [comment]
I think it is fixed now. 

@LironGetJones In documentation page try navigating to DatePicker with keyboard input set to true. Once you tab out, label shrinks correctly, with RC9 it used to stay shrinked.

**Comment by ajkaushik** [comment]
Spoke too soon, it seems to work in some cases, but not always. The behavior is not consistent. This should be re-opened.

**Comment by dmtrKovalenko** [comment]
Closed due to invalid request. IMHO focusing on the docs website on opening, closing tabbing into pickers works perfectly
