### ISSUE TITLE
Dayjs interface

### ISSUE THREAD

**Issue by yosmanyga** [dmtrKovalenko/material-ui-pickers#539]
I wonder if it's worth it to have an interface for [dayjs](https://github.com/iamkun/dayjs).

**Comment by stefensuhat** [comment]
+1. I'm using dayjs and need to add moment only for this loveable package.

**Comment by dmtrKovalenko** [comment]
@stefensuhat we will add this interface, but you can use date-fns - it will be much more lightweight and faster then moment

**Comment by dmtrKovalenko** [comment]
@yosmanyga After some investigation I found that dayjs still not have ability to parse strings with custom format https://github.com/iamkun/dayjs/issues/136. This seems to be a blocker, because without such functionality `keyboard` mode will be disabled. 

I propose usage of date-fns then 🙁 
Sorry for long response

**Comment by xxyuk** [comment]
CustomParseFormat plugin is supported and included in version 1.8.0 of dayjs

**Comment by jjosef** [comment]
This is released with https://github.com/dmtrKovalenko/date-io now
