### ISSUE TITLE
HTML5 validation with required attribute

### ISSUE THREAD

**Issue by gersongams** [dmtrKovalenko/material-ui-pickers#610]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    ^1.0.0-rc.12     |
| material-ui         |    1.4.2     |
| React               |   ^16.4.2      |
| Browser             |     68.0.3440.106     |
| Peer library        |   ^2.22.2    | 

## Steps to reproduce
1. I'm trying to use the required attribute in the DatePicker component but doesn't show any html5 validation when is empty
2. I set the value as null by default

## Expected behavior

Show a html5 validation message on form submit

## Actual behavior

Doesn't show anything on form submit

## Live example

A message like this

https://codesandbox.io/s/mzl0262m78

**Comment by dmtrKovalenko** [comment]
We support passing any property to material ui TextField so if you are seeing unexpected behavior with text pls raise an issue in material-ui

**Comment by byverdu** [comment]
Hi, 

for anyone that is trying to add the `required` attribute and don't see the input validated is because in this library if you don't specify the `keyboard` prop a `readonly` html attribute is added to the input tag. 

And per what the [HTML specifications says about this attribute](https://html.spec.whatwg.org/multipage/input.html#the-readonly-attribute) is that,

> Constraint validation: If the readonly attribute is specified on an input element, the element is barred from constraint validation.

So.... by adding the `keyboard` prop you'll be able to validate the datepicker :)
