### ISSUE TITLE
Hide hours and minutes selectors (like for seconds)

### ISSUE THREAD

**Issue by tonai** [dmtrKovalenko/material-ui-pickers#614]
To begin with thanks for your that nice library.

**Is your feature request related to a problem? Please describe.**
I would need a picker for selecting a time only expressed in minute and seconds or only in seconds.

**Describe the solution you'd like**
Adding the `hours` and `minutes` properties would be a nice solution (like for the `seconds` property).

**Describe alternatives you've considered**
Not for now...

Thanks :)

**Comment by dmtrKovalenko** [comment]
I realized that this feature would be useless. If you need the clock just use it directly

**Comment by orestes22** [comment]
Hi, Maybe add that feature only to minutes doesnt be useless, because sometime you have to select only the hour, for example if you are going to generate a cron expression you dont need the minutes in some cases. 
But it useless need change the UI design if I already using your component.

So, if you reconsider the option to disable the minutes selection like the seconds please let me know and can try to do a PR
Regards
