### ISSUE TITLE
Reset to passed in value on blur

### ISSUE THREAD

**Issue by cedrics** [dmtrKovalenko/material-ui-pickers#642]
**Is your feature request related to a problem? Please describe.**

When inputing a date via the keyboard which can not be parsed, it hides the actual value. There is as far as I can tell no way to change this behaviour

**Describe the solution you'd like**

It should reset the value displayed by the text field to the value which is passed in via the `value` property when the text field loses focus

**Describe alternatives you've considered**
If this is not a desired default behaviour and adding a toggle is not an option, the value displayed in the input could be made controllable. So a new prop `inputValue: string | null` if it is null, display the default value, otherwise display its text.

**Additional context**
If there is a way to achieve this behaviour, then I have missed it and would be happy for a pointer in the right direction.

Thx for the great work!

**Comment by Jtango18** [comment]
@rkinsman I suspect your particular issue is being caused by the bug outlined here: https://github.com/dmtrKovalenko/material-ui-pickers/issues/613 and that under the hood you're getting the date set to something earlier, but that's being masked the error message.

To test if this is actually the problem, you can do 2 things:

1. Set your error message to be an empty string. E.g. ""
2. Check whether you're displaying years in your date using a `Y` instead of `y`

I had the same issue you are describing and issue 613 was the underlying cause. HTH.

**Comment by rkinsman** [comment]
@Jtango18, I'm not convinced that is the issue I am having. I am using a custom format function that overrides the MomentUtils format function.

**Comment by dmtrKovalenko** [comment]
We can control the value of input if you want to with `inputProps` or `onKeyboardChange`.
Related to returning to previous value - that should be done on your side, when you change the `value` keyboard input will be updated as well
