### ISSUE TITLE
Inline pickers set a value when closing popup without selecting anything when current value is null

### ISSUE THREAD

**Issue by DanilloCorvalan** [dmtrKovalenko/material-ui-pickers#773]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.0.2      |
| material-ui         |    3.5.1     |
| React               |   16.5.2      |
| Browser             |    Chrome:latest     |

## Steps to reproduce
1. Have a inline date picker
2. Set initial value as null
3. Open picker and close it without selecting a date
4. It will select the today's date

## Expected behavior
To not select a default date when closing the modal if value is `null`. Keep it empty.

## Actual behavior
It's selecting a default date when closing the modal. But after emptying it again, the behaviour stops.

## Live example
https://codesandbox.io/s/y378n92n0z

**Comment by 555ea** [comment]
I experience this issue as well, and as I found, the cause is unnecessary call of `this.props.handleAccept();` at https://github.com/dmtrKovalenko/material-ui-pickers/blob/9d349053aa7739b0dc0ad03339f720c0c6f469be/lib/src/wrappers/InlineWrapper.tsx#L87 which is not present in ModalWrapper both `close()` and `handleDismiss()` methods, so line 87 should be removed at InlineWrapper

**Comment by marc-mrt** [comment]
I'm experiencing the same issue right now, I updated the modules in the codesandbox: https://codesandbox.io/s/p5z0x531x and it's still selecting today's date when closing the picker from outside

**Comment by emil-alexandrescu** [comment]
I am experiencing same issue
