### ISSUE TITLE
Not hightliting today date if value is null.

### ISSUE THREAD

**Issue by koshkarik** [dmtrKovalenko/material-ui-pickers#774]
Hello! Is it actually possible to not hightlight today date if value given to datepicker is null? Was looking in your code, but that line i think makes it impossible... `const initialDate = value || initialFocusedDate || utils.date();`  May be is there any flag for it? I am using your static components

**Comment by msteinmn** [comment]
yes, I'd like to see a mask to enter a date

**Comment by dmtrKovalenko** [comment]
I thought about it a bit. And from my prospective thats incorrect. If no value will be highlighted it should also shows something like `-- : --` in timepicker header. But I cannot find any material design datepicker  that support clear state. 
Also thats pretty clear. If user opens datepicker it preselect today by default. Or the closest available day. 
And also it is quite a lot part of work. For now I am closing this issue, if you have any concerns pls let me know here.

**Comment by tayfunyugruk** [comment]
@dmtrKovalenko i am having this exact problem, i have a form which have 2 fields which one is for start and one is for end date selection, end date can be empty (which means limitless and will be selected later) but i can not set it to empty/null date due to default value handling which makes selecting a null date impossible. i think it will be better to let component display null value and developer can handle null value situation by displaying string like "---" or smt else using label formatter.
