### ISSUE TITLE
Disable Certain Dates/Days

### ISSUE THREAD

**Issue by AxelAli** [dmtrKovalenko/material-ui-pickers#797]
**Is your feature request related to a problem? Please describe.**
I am trying to get it to allow specific Hours/Minutes/Seconds, disable the rest

**Describe the solution you'd like**
Passing an array of disabled Hours/Minutes/Seconds like:
```
disableTimes = { hours: [1, 2, 3, 4, 5, 6, 7, 8], minutes: [20, 25] };
//or
enableTimes = { hours: [9, 10, 11, 12], minutes: [0, 15, 30, 45] };
```

**Additional context**
Imagine we are trying to make reservation for a restaurant, the backend returns the times that they are free, and only allows the user to select those free days/hours

**Comment by dmtrKovalenko** [comment]
So you want to disable days or some period of time?

**Comment by AxelAli** [comment]
So, let's say I only work form 9-5, it's pointless to allow the user to select 4 AM and then tell them 'it needs to be in this time-frame'
my idea is mostly being able to disable certain dates, I won't work on the 25 of December, why allow the user to pick it in the first place. or, I already have a meeting at 3, don't allow that time to be selected

**Comment by dmtrKovalenko** [comment]
@AxelAli you can disable any day by custom `shouldDisableDate` function passed to the date or datetime picker.

**Comment by lirenwang** [comment]
@dmtrKovalenko Hi,
so we have this situation that we disabled all the weekends and holidays. However user can still type in an invalid date. And if they do so, once you open the picker it will be automatically picked at 2100/1/1. Is there any solution/suggestion about this issue? Thanks.

**Comment by lirenwang** [comment]
> @dmtrKovalenko Hi,
> so we have this situation that we disabled all the weekends and holidays. However user can still type in an invalid date. And if they do so, once you open the picker it will be automatically picked at 2100/1/1. Is there any solution/suggestion about this issue? Thanks.

I actually found the solution. When using `shouldDisableDate` prop, we better add a `mindate`, because it will become the default fallback date. 

Its cause by the `findClosestEnabledDate` in https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/_helpers/date-utils.ts
the function will compare the invalid date with `minDate`(defaulted to 1900/1/1) and `maxDate`(defaulted to 2100/1/1) and return the closet one.

**Comment by dmtrKovalenko** [comment]
Ok, I will take a look on that today

**Comment by wichert** [comment]
I suspect the mindate issue here is the same as #823 ?

I am running into the min/max time issue here as well, for pretty much the same use case (reservation system). I see a two extra complexities:

1. the minimum and maximum possible times are not the same for every day, so I need the ability to derive them from the week day. This would either require a callback for a DateTimePicker to determine minTime and maxTime after date selection, or use of separate date and time pickers.
2. I may have time slots in the middle of the day that are fully booked, so I need the ability to disable specific time intervals. I'm not sure what kind of hooks would be needed to handle this cleanly. I may just end up using a selection dropdown which only lists available time slots instead of using a TimePicker.

**Comment by dmtrKovalenko** [comment]
Issue is not replicable. For disable certain dates use `shouldDisableDate` for time there is #519
