### ISSUE TITLE
Discrepancy between react dev and peer dependencies

### ISSUE THREAD

**Issue by depsir** [dmtrKovalenko/material-ui-pickers#939]
Looking at the package json of the `lib` folder I see that react appears as `devDependencies` and also `peerDependencies` but with different versions.

```
{
  "peerDependencies": {
    "react": "^16.3.0",
    "react-dom": "^16.3.0"
  },
  "devDependencies": {
    "@types/react": "^16.8.2",
    "@types/react-dom": "^16.8.0",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
  },
}
```

I understand that `react` is needed as dev dependency for development. And every feature shipped in react 16.8.2 could be used in code.

But when I install this package and I'm using a lower version of `react`, say `16.3.0`, the peer dependency is satisfied and everything is supposed to work. But every feature introduced after `16.3.0` will not be available in my environment and if material-ui-pickers uses them, it will break

I see two ways of solving this:
1. if material-ui-pickers needs stuff from react 16.8, then also the peer dependency needs to be higher
2. if not, then the devDependency should be lower

In any case I think that peer and dev dependency should have the same value (maybe peer with range while dev fixed).

Am I missing something? 

As a side note I'm experiencing trouble in making material-ui-pickers work with react 16.6.1, this is what made me look into its dependencies

**Comment by dmtrKovalenko** [comment]
Thanks for rising the issue. We are not going to use different peerDependencies then [material-ui](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/package.json#L34). 
Why devDependency is different? That is just because of default updating packages process. See that material-ui [also](https://github.com/mui-org/material-ui/blob/next/package.json#L163) using 16.8.0 react for development.

We will not use any feature of > 16.3 react before updating peerDependencies.
